export const OPEN_WEATHER_KEY = 'fc2a56b9872f1b94a184ef6144af6200';
export const OPEN_WEATHER_URL = 'https://api.openweathermap.org/data/2.5'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const FETCH_CURRENT_WEATHER_BEGIN = 'FETCH_CURRENT_WEATHER_BEGIN';
export const FETCH_CURRENT_WEATHER_SUCCESS = 'FETCH_CURRENT_WEATHER_SUCCESS';
export const FETCH_CURRENT_WEATHER_FAILURE = 'FETCH_CURRENT_WEATHER_FAILURE';
export const CLEAR_CURRENT_WEATHER = 'CLEAR_CURRENT_WEATHER';

export const FETCH_LONG_TERM_WEATHER_BEGIN = 'FETCH_LONG_TERM_WEATHER_BEGIN';
export const FETCH_LONG_TERM_WEATHER_SUCCESS = 'FETCH_LONG_TERM_WEATHER_SUCCESS';
export const FETCH_LONG_TERM_WEATHER_FAILURE = 'FETCH_LONG_TERM__WEATHER_FAILURE';